# Generated by Django 5.0.1 on 2024-02-07 23:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_delete_state"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="display_name",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="full_name",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="password_reset_otp",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="password_reset_otp_created_at",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="phone_number",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="state_of_residence",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="user_field",
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_field",
                    models.CharField(
                        choices=[
                            ("BILLBOARD_OWNER", "Billboard Owner"),
                            ("STATE_AGENT", "State Agent"),
                            ("ADVERTISING_AGENT", "Advertising Agent"),
                            ("BUSINESS_OWNER", "Business Owner"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("full_name", models.CharField(blank=True, max_length=255, null=True)),
                ("display_name", models.CharField(max_length=255, null=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("FCT", "Fct"),
                            ("OYO", "Oyo"),
                            ("IMO", "Imo"),
                            ("EDO", "Edo"),
                            ("KANO", "Kano"),
                            ("ONDO", "Ondo"),
                            ("OSUN", "Osun"),
                            ("OGUN", "Ogun"),
                            ("KOGI", "Kogi"),
                            ("YOBE", "Yobe"),
                            ("ABIA", "Abia"),
                            ("ENUGU", "Enugu"),
                            ("LAGOS", "Lagos"),
                            ("NIGER", "Niger"),
                            ("BENUE", "Benue"),
                            ("GOMBE", "Gombe"),
                            ("KWARA", "Kwara"),
                            ("EKITI", "Ekiti"),
                            ("DELTA", "Delta"),
                            ("BORNO", "Borno"),
                            ("KEBBI", "Kebbi"),
                            ("KADUNA", "Kaduna"),
                            ("BAUCHI", "Bauchi"),
                            ("EBONYI", "Ebonyi"),
                            ("JIGAWA", "Jigawa"),
                            ("SOKOTO", "Sokoto"),
                            ("RIVERS", "Rivers"),
                            ("TARABA", "Taraba"),
                            ("ZAMFARA", "Zamfara"),
                            ("PLATEAU", "Plateau"),
                            ("ADAMAWA", "Adamawa"),
                            ("ANAMBRA", "Anambra"),
                            ("KATSINA", "Katsina"),
                            ("BAYELSA", "Bayelsa"),
                            ("NASARAWA", "Nasarawa"),
                            ("AKWA_IBOM", "Akwa Ibom"),
                            ("CROSS_RIVER", "Cross River"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        choices=[("NG", "Nigeria")], default="NG", max_length=10
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=11, null=True, unique=True),
                ),
                ("password_reset_otp", models.CharField(max_length=6, null=True)),
                ("password_reset_otp_created_at", models.DateTimeField(null=True)),
                (
                    "user",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
