# Generated by Django 5.0.1 on 2024-02-07 23:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billboards", "0009_rename_booked_billboard_is_booked"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billboard",
            name="state",
            field=models.CharField(
                choices=[
                    ("FCT", "Fct"),
                    ("OYO", "Oyo"),
                    ("IMO", "Imo"),
                    ("EDO", "Edo"),
                    ("KANO", "Kano"),
                    ("ONDO", "Ondo"),
                    ("OSUN", "Osun"),
                    ("OGUN", "Ogun"),
                    ("KOGI", "Kogi"),
                    ("YOBE", "Yobe"),
                    ("ABIA", "Abia"),
                    ("ENUGU", "Enugu"),
                    ("LAGOS", "Lagos"),
                    ("NIGER", "Niger"),
                    ("BENUE", "Benue"),
                    ("GOMBE", "Gombe"),
                    ("KWARA", "Kwara"),
                    ("EKITI", "Ekiti"),
                    ("DELTA", "Delta"),
                    ("BORNO", "Borno"),
                    ("KEBBI", "Kebbi"),
                    ("KADUNA", "Kaduna"),
                    ("BAUCHI", "Bauchi"),
                    ("EBONYI", "Ebonyi"),
                    ("JIGAWA", "Jigawa"),
                    ("SOKOTO", "Sokoto"),
                    ("RIVERS", "Rivers"),
                    ("TARABA", "Taraba"),
                    ("ZAMFARA", "Zamfara"),
                    ("PLATEAU", "Plateau"),
                    ("ADAMAWA", "Adamawa"),
                    ("ANAMBRA", "Anambra"),
                    ("KATSINA", "Katsina"),
                    ("BAYELSA", "Bayelsa"),
                    ("NASARAWA", "Nasarawa"),
                    ("AKWA_IBOM", "Akwa Ibom"),
                    ("CROSS_RIVER", "Cross River"),
                ],
                max_length=255,
            ),
        ),
    ]
